name: "Bug Report"
description: "버그를 발견하셨나요? 여기서 신고해주세요."
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "## 🐛 버그 설명\n문제가 발생한 내용을 명확하고 간결하게 설명해주세요."

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "✅ 재현 방법"
      description: "버그를 재현하는 방법을 단계별로 설명해주세요."
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. See error"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "🤔 예상 동작"
      description: "정상적으로 동작했을 때 기대했던 결과를 설명해주세요."
    validations:
      required: true
